routes/web.php
<?php

use App\Http\Controllers\ReportController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

//Home page
Route::get('/', function () {
    return view('auth/login');
});

Route::get('/reset_password', 'PasswordResetController@index')->name('resetPassword');
Route::post('/reset_password', 'PasswordResetController@search_user')->name('getUser');
Route::post('/reset_password/confirmed', 'PasswordResetController@update')->name('password_reset');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('change_password', 'PasswordChangeController');
});


Route::group(['middleware' => 'auth', 'middleware' => ['role:supadmin|salescenter|servicepoint']], function () {
    Route::post('/chk_disclaimer', 'HomeController@disclaimer')->name('chk_disclaimer');
    Route::resource('sales', 'SaleController');
    Route::post('/get_fscode', 'SaleController@get_fs')->name('get_fscode');
    Route::post('/get_service_type_price_range', 'SaleController@get_service_type_price_range')->name('get_service_type_price_range');
    Route::post('/sales_report', 'SaleController@date_wise_sales_report')->name('sales_report');
    Route::post('/get_mrp', 'SaleController@get_mrp')->name('get_mrp');
    Route::post('/get_imei_info', 'SaleController@get_info_by_imei')->name('get_imei_info');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|servicepoint|callcenter']], function () {
    Route::post('/chk_service_disclaimer', 'ServicePointController@disclaimer_service')->name('chk_service_disclaimer');
    Route::resource('servicepoint', 'ServicePointController');
    Route::post('servicepoint', 'ServicePointController@search')->name('search');
    Route::post('servicepoint/search_by_phone_number', 'ServicePointController@search_by_phone_number')->name('search_by_phone');
    Route::post('servicepoint/search_by_serviceType', 'ServicePointController@search_by_serviceType')->name('search_by_service_type');
    Route::post('servicepoint/record_history', 'ServicePointController@store')->name('record_history');
    Route::post('servicepoint/delivery', 'ServicePointController@handset_delivery')->name('delivery');
    Route::post('servicepoint/notification', 'ServicePointController@send_early_notification')->name('notification');
    Route::post('servicepoint/verify', 'ServicePointController@verify')->name('verify_otp');
    Route::post('servicepoint/displayImage', 'ServicePointController@display_sales_image')->name('displayImage');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin']], function () {
    Route::get('/store_wise', 'ReportController@store_wise')->name('store');
    Route::post('/store_wise', 'ReportController@store_wise_report')->name('store_wise_report');
    Route::get('/date_wise', 'ReportController@date_wise')->name('date');
    Route::post('/date_wise', 'ReportController@date_wise_report_search')->name('date_wise_reaport');
    Route::get('/imei_wise', 'ReportController@imei_wise')->name('imei');
    Route::post('/imei_wise', 'ReportController@imei_wise_report')->name('imei_wise_report');
    Route::get('/head_office', 'ReportController@head_office')->name('head');
    Route::post('/showImage', 'ReportController@display_image')->name('show_image');
    Route::post('/deleteSale/{fscode}', 'ReportController@delete_sale')->name('delete_sale');
});


Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin']], function () {
    Route::resource('users', 'UsersController');
    Route::resource('permission', 'PermissionController');
    Route::resource('roles', 'RolesController');
    Route::resource('outlet', 'OutletController');
    Route::resource('import', 'ImportExportController');
    Route::delete('import', 'ImportExportController@destroy_all')->name('delete_all');
    Route::resource('txtimport', 'TxtFileImportController');
    Route::delete('txtimport', 'TxtFileImportController@destroy_all')->name('txt_delete_all');
    Route::resource('download', 'FileDownloadController');
    Route::resource('imeichange', 'ImeiChangeController');
    Route::post('/imeichange', 'ImeiChangeController@get_details_by_imei')->name('imeidetail');
    Route::get('/extractfile', 'FileExtractionController@index')->name('file_extraction');
    Route::post('/extractfile', 'FileExtractionController@fileExtraction')->name('file_extraction');
    Route::resource('tiers', 'TierController');
    Route::resource('phone_models', 'PhoneModelController');
    Route::resource('import_imei', 'ImeiController');
    Route::get('/download_sample_imei', 'FileDownloadController@imei_sample')->name('download_sample_imei');
    Route::get('/download_sample_bulk_user_creation', 'FileDownloadController@bulk_user_creation_sample')->name('download_sample_bulk_user_creation');
    Route::get('/bulk_user_creation', 'UsersController@get_bulk_user_creation_view')->name('create_bulk_user');
    Route::post('/bulk_user_creation', 'UsersController@bulk_user_creation')->name('bulk_user');
    Route::resource('bongoTvCodes', 'BongoTvCodeController');
    Route::delete('bongoTvCodes', 'BongoTvCodeController@destroy_unusedCodes')->name('delete_unused_codes');
    Route::get('/download_sample_bongoTvCodes', 'FileDownloadController@bongoTvCodesSample')->name('download_sample_bongoTvCodes');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|insurance|admin']], function () {
    Route::get('/ins_sales_report', 'ReportController@insurance_sales')->name('ins_sales');
    Route::post('/ins_sales_report', 'ReportController@insurance_sales_report')->name('insurance_sales_report');
    Route::post('/insImageDisplay', 'ReportController@display_image')->name('ins_display_image');
    Route::get('/ins_service_report', 'ReportController@insurance_service')->name('ins_service');
    Route::post('/ins_service_report', 'ReportController@insurance_service_report')->name('insurance_service_report');
    Route::post('/insServiceImageDisplay', 'ReportController@ins_display_image')->name('ins_display_service_image');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin|insurance']], function () {
    Route::get('/date_wise_claim_search', 'ReportController@get_date_wise_claim_report')->name('date_wise_claim_search');
    Route::post('/date_wise_claim_search', 'ReportController@date_wise_claim_report_search')->name('date_wise_claim_report');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin|insurance|servicepoint|callcenter']], function () {
    Route::get('/date_wise_claim_search', 'ReportController@get_date_wise_claim_report')->name('date_wise_claim_search');
    Route::post('/date_wise_claim_search', 'ReportController@date_wise_claim_report_search')->name('date_wise_claim_report');
    Route::post('/insServiceImageDisplay', 'ReportController@ins_display_image')->name('ins_display_service_image');
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:supadmin|salescenter|callcenter|servicepoint']], function () {
    Route::post('/verify_sales', 'SaleController@verifyOtp')->name('otpVerify');
    Route::post('/resend_otp', 'SaleController@resendOtp')->name('resend_otp');
    Route::post('/submit_without_otp', 'SaleController@submitWithoutOtp')->name('submit_without_otp');
    Route::post('/verify_sale/{id}', 'SaleController@saleVerification')->name('sale_verification');
    Route::resource('sales', 'SaleController');
    Route::post('/sales_report', 'SaleController@date_wise_sales_report')->name('sales_report');
});

app/Role.php
<?php

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    protected $fillable = [
        'name', 'display_name', 'description'
    ];
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Database\Eloquent\ModelNotFoundException as ModelNotFoundException;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Role;
use App\Permission;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();

        $params = [
            'title' => 'Roles Listing',
            'roles' => $roles,
        ];

        return view('admin.roles.roles_list')->with($params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();

        $params = [
            'title' => 'Create Role',
            'permissions' => $permissions
        ];

        return view('admin.roles.roles_create')->with($params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles',
            'display_name' => 'required',
            'description' => 'required',
        ]);

        //dd($request->input('permission'));

        $role = Role::create([
            'name' => $request->input('name'),
            'display_name' => $request->input('display_name'),
            'description' => $request->input('description'),
        ]);

        // Permission::create([
        //     'permission_id' => $request->input('permission'),
        //     'role_id'=>$role->id
        // ]);

        // $user = new User();

        // $user->roles()->attach([$role->id]);
        // $user->permissions()->attach([$role->id]);
        // $permission = $request->input('permission');
        // foreach ($request->input('permission') as $key => $value) {
        //     $role->permissions()->attach([$value]);
        // }
        // foreach ($request->input('permission') as $key => $value) {
        // Permission::insert([
        //     'permission_id' => $value,
        //     'role_id'=>$role->id,
        // ]);
        // }

        // $role->permissions()->attach([$permission]);

        return redirect()->route('roles.index')->with('success', "The role $role->name has successfully been created.");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $roles = Role::findOrFail($id);

            $params = [
                'title' => 'Details',
                'roles' => $roles,
            ];

            return view('admin.roles.roles_view')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $role = Role::findOrFail($id);
            // $permissions = Permission::all();
            // $role_permissions = $role->permissions()->get()->pluck('id')->toArray();

            $params = [
                'title' => 'Edit Role',
                'roles' => $role,
            ];

            return view('admin.roles.roles_edit')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $role = Role::findOrFail($id);

            $this->validate($request, [
                'role_name' => 'required',
                'display_name' => 'required',
                'description' => 'required',
            ]);

            $role->name = $request->input('role_name');
            $role->display_name = $request->input('display_name');
            $role->description = $request->input('description');

            $role->save();

            // DB::table("permission_role")->where("permission_role.role_id", $id)->delete();
            // // Attach permission to role
            // foreach ($request->input('permission_id') as $key => $value) {
            //     $role->attachPermission($value);
            // }

            return redirect()->route('roles.index')->with('msg', "The role $role->name has successfully been updated.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $role = Role::findOrFail($id);

            //$role->delete();

            // Force Delete
            // $role->users()->sync([]); // Delete relationship data
            // $role->permissions()->sync([]); // Delete relationship data

            // $role->forceDelete(); // Now force delete will work regardless of whether the pivot table has cascading delete

            return redirect()->route('roles.index')->with('success', "The Role $role->name has successfully been archived.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
}

resources/views/admin/roles/roles_create.blade.php
@extends('layouts.dashboard.dash')

@section('title','Role Create')

@push('css')

@endpush
@section('content')

<div class="container-fluid">
    <!-- Horizontal Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        {{ $title }}
                    </h2>
                </div>
                <div class="body">
                    <form class="form-horizontal" action="{{ route('roles.store')}}" method="POST">
                        @csrf
                        <div class="row{{ $errors->has('name') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="name">Name</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="name" id="name"
                                            value="{{ Request::old('name') ?: '' }}" class="form-control"
                                            placeholder="Enter role name">
                                    </div>
                                </div>
                                @if ($errors->has('name'))
                                <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row{{ $errors->has('display_name') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="display_name">Display Name</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="display_name" id="display_name"
                                            value="{{ Request::old('display_name') ?: '' }}" class="form-control"
                                            placeholder="Enter display name">
                                    </div>
                                </div>
                                @if ($errors->has('display_name'))
                                <span class="help-block">{{ $errors->first('display_name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row{{ $errors->has('description') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="description">Description</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="description" id="description" class="form-control"
                                            value="{{ Request::old('description') ?: '' }}"
                                            placeholder="Enter description">
                                    </div>
                                </div>
                                @if ($errors->has('description'))
                                <span class="help-block">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                        </div>
                        <!-- <div class="row{{ $errors->has('description') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="description">Permission</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="demo-checkbox">
                                      @foreach ($permissions as $key=>$permission)
                                      <input type="checkbox" id="{{ $key }}" class="filled-in" name="permission[]" value="{{ $permission->id }}">
                                      <label for="{{ $key }}">{{ $permission->display_name }}</label>
                                      @endforeach
                                    </div>
                                </div>
                            </div>
                        </div> -->

                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                <a href="{{route('roles.index')}}"><button type="button"
                                        class="btn btn-primary m-t-15 waves-effect">
                                        << Back</button> </a> </div> <div
                                            class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Create
                                                Role</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@push('js')

@endpush

resources/views/admin/roles/roles_delete.blade.php
@extends('layouts.adminpages') 
@section('title','Role Delete')
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Roles</h1>
    </div>
    <a class="btn btn-sm btn-primary" href="{{route('roles.index')}}">Back</a>
    <h2>{{$title}}</h2>
    <div class="clearfix"></div>
    <p>Are you sure you want to delete
        <strong>{{$role->name}}</strong>
    </p>

    <form method="POST" action="{{ route('roles.destroy', ['id' => $role->id]) }}">
        <input type="hidden" name="_token" value="{{ Session::token() }}">
        <input name="_method" type="hidden" value="DELETE">
        <button type="submit" class="btn btn-danger">Yes I'm sure. Delete</button>
    </form>
</main>
</div>
</div>

@endsection

resources/views/admin/roles/roles_edit.blade.php
@extends('layouts.dashboard.dash')
@section('title',$title)

@push('css')

@endpush
@section('content')

<div class="container-fluid">
    <!-- Horizontal Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        {{ $title }}
                    </h2>
                </div>
                <div class="body">
                    <form class="form-horizontal" action="{{ route('roles.update', $roles->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row{{ $errors->has('role_name') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="role_name">Role Name</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="role_name" id="role_name" value="{{ $roles->name }}" class="form-control" placeholder="Enter role name">
                                    </div>
                                </div>
                                @if ($errors->has('role_name'))
                                <span class="help-block">{{ $errors->first('role_name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row{{ $errors->has('display_name') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="display_name">Display Name</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="display_name" id="display_name" value="{{ $roles->display_name }}" class="form-control" placeholder="Enter display name">
                                    </div>
                                </div>
                                @if ($errors->has('display_name'))
                                <span class="help-block">{{ $errors->first('display_name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row{{ $errors->has('description') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="description">Description</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="description" id="description" class="form-control" value="{{ $roles->description }}" placeholder="Enter description">
                                    </div>
                                </div>
                                @if ($errors->has('description'))
                                <span class="help-block">{{ $errors->first('description') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                <a href="{{route('roles.index')}}"><button type="button" class="btn btn-primary m-t-15 waves-effect">
                                        << Back</button> </a> </div> <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')

@endpush

resources/views/admin/roles/roles_list.blade.php
@extends('layouts.dashboard.dash')

@section('title', $title)
    

@push('css')

@endpush

@section('content')

<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                        <h2>
                            {{ $title }}
                        </h2>
                    </div>
                   {{-- @role('basic_user') --}}
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                        <a href="{{route('roles.create')}}"><button type="button" class="btn bg-green waves-effect">Add
                                New</button></a>
                    </div>
                    {{-- @endrole --}}
                </div>
            </div>
            @if ($message = Session::get('msg'))
            <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {{ $message }}</em></div>
            @endif
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Role Name</th>
                                <th>Display Name</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Role Name</th>
                                <th>Display Name</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <?php $i=1; ?>
                            @foreach ($roles as $role)

                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $role->name }}</td>
                                <td>{{ $role->display_name }}</td>
                                <td>{{ $role->description }}</td>
                                <td>
                                    <form action="{{ route('roles.destroy',$role->id) }}" method="POST">

                                        <a class="btn btn-defauld" href="{{ route('roles.show', $role->id) }}"><i
                                                class="fa fa-bars" aria-hidden="true" title="view"></i></a>

                                        &nbsp;&nbsp; <a class="btn btn-primary"
                                            href="{{ route('roles.edit', $role->id) }}"><i class="fa fa-pencil-square-o"
                                                aria-hidden="true" title="edit"></i></a>

                                        @csrf
                                        @method('DELETE')

                                        &nbsp;&nbsp; <button class="btn btn-danger" type="submit"
                                            onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"
                                                aria-hidden="true" title="delete"></i></button>
                                    </form>
                                </td>
                            </tr>

                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->
@endsection

@push('js')

@endpush