routes/web.php
<?php

use App\Http\Controllers\ReportController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

//Home page
Route::get('/', function () {
    return view('auth/login');
});

Route::get('/reset_password', 'PasswordResetController@index')->name('resetPassword');
Route::post('/reset_password', 'PasswordResetController@search_user')->name('getUser');
Route::post('/reset_password/confirmed', 'PasswordResetController@update')->name('password_reset');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('change_password', 'PasswordChangeController');
});


Route::group(['middleware' => 'auth', 'middleware' => ['role:supadmin|salescenter|servicepoint']], function () {
    Route::post('/chk_disclaimer', 'HomeController@disclaimer')->name('chk_disclaimer');
    Route::resource('sales', 'SaleController');
    Route::post('/get_fscode', 'SaleController@get_fs')->name('get_fscode');
    Route::post('/get_service_type_price_range', 'SaleController@get_service_type_price_range')->name('get_service_type_price_range');
    Route::post('/sales_report', 'SaleController@date_wise_sales_report')->name('sales_report');
    Route::post('/get_mrp', 'SaleController@get_mrp')->name('get_mrp');
    Route::post('/get_imei_info', 'SaleController@get_info_by_imei')->name('get_imei_info');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|servicepoint|callcenter']], function () {
    Route::post('/chk_service_disclaimer', 'ServicePointController@disclaimer_service')->name('chk_service_disclaimer');
    Route::resource('servicepoint', 'ServicePointController');
    Route::post('servicepoint', 'ServicePointController@search')->name('search');
    Route::post('servicepoint/search_by_phone_number', 'ServicePointController@search_by_phone_number')->name('search_by_phone');
    Route::post('servicepoint/search_by_serviceType', 'ServicePointController@search_by_serviceType')->name('search_by_service_type');
    Route::post('servicepoint/record_history', 'ServicePointController@store')->name('record_history');
    Route::post('servicepoint/delivery', 'ServicePointController@handset_delivery')->name('delivery');
    Route::post('servicepoint/notification', 'ServicePointController@send_early_notification')->name('notification');
    Route::post('servicepoint/verify', 'ServicePointController@verify')->name('verify_otp');
    Route::post('servicepoint/displayImage', 'ServicePointController@display_sales_image')->name('displayImage');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin']], function () {
    Route::get('/store_wise', 'ReportController@store_wise')->name('store');
    Route::post('/store_wise', 'ReportController@store_wise_report')->name('store_wise_report');
    Route::get('/date_wise', 'ReportController@date_wise')->name('date');
    Route::post('/date_wise', 'ReportController@date_wise_report_search')->name('date_wise_reaport');
    Route::get('/imei_wise', 'ReportController@imei_wise')->name('imei');
    Route::post('/imei_wise', 'ReportController@imei_wise_report')->name('imei_wise_report');
    Route::get('/head_office', 'ReportController@head_office')->name('head');
    Route::post('/showImage', 'ReportController@display_image')->name('show_image');
    Route::post('/deleteSale/{fscode}', 'ReportController@delete_sale')->name('delete_sale');
});


Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin']], function () {
    Route::resource('users', 'UsersController');
    Route::resource('permission', 'PermissionController');
    Route::resource('roles', 'RolesController');
    Route::resource('outlet', 'OutletController');
    Route::resource('import', 'ImportExportController');
    Route::delete('import', 'ImportExportController@destroy_all')->name('delete_all');
    Route::resource('txtimport', 'TxtFileImportController');
    Route::delete('txtimport', 'TxtFileImportController@destroy_all')->name('txt_delete_all');
    Route::resource('download', 'FileDownloadController');
    Route::resource('imeichange', 'ImeiChangeController');
    Route::post('/imeichange', 'ImeiChangeController@get_details_by_imei')->name('imeidetail');
    Route::get('/extractfile', 'FileExtractionController@index')->name('file_extraction');
    Route::post('/extractfile', 'FileExtractionController@fileExtraction')->name('file_extraction');
    Route::resource('tiers', 'TierController');
    Route::resource('phone_models', 'PhoneModelController');
    Route::resource('import_imei', 'ImeiController');
    Route::get('/download_sample_imei', 'FileDownloadController@imei_sample')->name('download_sample_imei');
    Route::get('/download_sample_bulk_user_creation', 'FileDownloadController@bulk_user_creation_sample')->name('download_sample_bulk_user_creation');
    Route::get('/bulk_user_creation', 'UsersController@get_bulk_user_creation_view')->name('create_bulk_user');
    Route::post('/bulk_user_creation', 'UsersController@bulk_user_creation')->name('bulk_user');
    Route::resource('bongoTvCodes', 'BongoTvCodeController');
    Route::delete('bongoTvCodes', 'BongoTvCodeController@destroy_unusedCodes')->name('delete_unused_codes');
    Route::get('/download_sample_bongoTvCodes', 'FileDownloadController@bongoTvCodesSample')->name('download_sample_bongoTvCodes');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|insurance|admin']], function () {
    Route::get('/ins_sales_report', 'ReportController@insurance_sales')->name('ins_sales');
    Route::post('/ins_sales_report', 'ReportController@insurance_sales_report')->name('insurance_sales_report');
    Route::post('/insImageDisplay', 'ReportController@display_image')->name('ins_display_image');
    Route::get('/ins_service_report', 'ReportController@insurance_service')->name('ins_service');
    Route::post('/ins_service_report', 'ReportController@insurance_service_report')->name('insurance_service_report');
    Route::post('/insServiceImageDisplay', 'ReportController@ins_display_image')->name('ins_display_service_image');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin|insurance']], function () {
    Route::get('/date_wise_claim_search', 'ReportController@get_date_wise_claim_report')->name('date_wise_claim_search');
    Route::post('/date_wise_claim_search', 'ReportController@date_wise_claim_report_search')->name('date_wise_claim_report');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin|insurance|servicepoint|callcenter']], function () {
    Route::get('/date_wise_claim_search', 'ReportController@get_date_wise_claim_report')->name('date_wise_claim_search');
    Route::post('/date_wise_claim_search', 'ReportController@date_wise_claim_report_search')->name('date_wise_claim_report');
    Route::post('/insServiceImageDisplay', 'ReportController@ins_display_image')->name('ins_display_service_image');
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:supadmin|salescenter|callcenter|servicepoint']], function () {
    Route::post('/verify_sales', 'SaleController@verifyOtp')->name('otpVerify');
    Route::post('/resend_otp', 'SaleController@resendOtp')->name('resend_otp');
    Route::post('/submit_without_otp', 'SaleController@submitWithoutOtp')->name('submit_without_otp');
    Route::post('/verify_sale/{id}', 'SaleController@saleVerification')->name('sale_verification');
    Route::resource('sales', 'SaleController');
    Route::post('/sales_report', 'SaleController@date_wise_sales_report')->name('sales_report');
});

app/PhoneModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PhoneModel extends Model
{
    protected $fillable = [
        'model_name', 'mrp', 'status', 'added_by',
    ];
}

app/Http/Controllers/Admin/PhoneModelController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Database\Eloquent\ModelNotFoundException as ModelNotFoundException;

use App\PhoneModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class PhoneModelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $phone_models = DB::table('phone_models')->select('phone_models.*', 'users.name')->join('users', 'users.id', '=', 'phone_models.added_by')->orderBy('id', 'DESC')->get();

        $params = [
            'title' => 'Phone Model List',
            'models' => $phone_models
        ];

        return view('admin/phone_models/list')->with($params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $params = [
            'title' => 'Create Phone Model'
        ];

        return view('admin/phone_models/create')->with($params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'model_name' => 'required|unique:phone_models,model_name',
            'fs_mrp' => 'required'
        ]);

        $phone_model = PhoneModel::create([
            'model_name' => $request->input('model_name'),
            'mrp' => $request->input('fs_mrp'),
            'status' => 1,
            'added_by' => Auth::user()->id
        ]);

        return redirect()->route('phone_models.index')->with('msg', "The model $phone_model->model_name has successfully been created.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PhoneModel  $phoneModel
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $phone_model = DB::table('phone_models')->select('phone_models.*', 'users.name')
                ->join('users', 'users.id', '=', 'phone_models.added_by')
                ->where('phone_models.id', $id)
                ->get();

            $params = [
                'title' => 'Model Details',
                'phone_models' => $phone_model,
            ];

            return view('admin.phone_models.view')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PhoneModel  $phoneModel
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $phone_model = PhoneModel::findOrFail($id);

            $params = [
                'title' => 'Edit Model',
                'phone_models' => $phone_model,
            ];

            return view('admin.phone_models.edit')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PhoneModel  $phoneModel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $phone_model = PhoneModel::findOrFail($id);

            $this->validate($request, [
                'model_name' => 'required',
                'fs_mrp' => 'required'
            ]);

            $phone_model->model_name = $request->input('model_name');
            $phone_model->mrp = $request->input('fs_mrp');
            $phone_model->status = $request->input('status');

            $phone_model->save();

            return redirect()->route('phone_models.index')->with('msg', "The model $phone_model->model_name has successfully been updated.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PhoneModel  $phoneModel
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $phone_model = PhoneModel::findOrFail($id);

            $phone_model->delete();

            return redirect()->route('phone_models.index')->with('msg', "The model $phone_model->model_name has successfully been deleted.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
}

resources/views/admin/phone_models/create.blade.php
@extends('layouts.dashboard.dash')
@section('title', $title)
@push('css')

@endpush
@section('content')

<style>
    .control-label:after {
        content: "*";
        color: red;
    }
</style>

<div class="container-fluid">
    <!-- Horizontal Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        {{ $title }}
                    </h2>
                </div>
                <div class="body">
                    <div class="col-lg-10 col-lg-offset-2 col-md-12">
                        <label for="required_field" class="control-label"></label><i> required field</i>
                    </div>
                    <form class="form-horizontal" action="{{ route('phone_models.store')}}" method="POST">
                        @csrf
                        <div class="row{{ $errors->has('model_name') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
                                <label for="model_name" class="control-label">Model </label>
                            </div>
                            <div class="col-lg-6 col-md-8 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="model_name" id="model_name" class="form-control" value="{{ Request::old('model_name') ?: '' }}" placeholder="ex-P30">
                                    </div>
                                </div>
                                @if ($errors->has('model_name'))
                                <span class="help-block">{{ $errors->first('model_name') }}</span>
                                @endif
                            </div>
                            <div class="col-lg-2"></div>
                        </div>
                        <div class="row{{ $errors->has('fs_mrp') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
                                <label for="fs_mrp" class="control-label">FS MRP&nbsp;<img src="{{ asset('assets/taka.png') }}" width="8" height="10"> </label>
                            </div>
                            <div class="col-lg-6 col-md-8 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="number" name="fs_mrp" id="fs_mrp" class="form-control" value="{{ Request::old('fs_mrp') ?: '' }}" placeholder="ex-1590">
                                    </div>
                                </div>
                                @if ($errors->has('fs_mrp'))
                                <span class="help-block">{{ $errors->first('fs_mrp') }}</span>
                                @endif
                            </div>
                            <div class="col-lg-2"></div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-4 col-md-4 col-sm-2 col-xs-2">
                                <a href="{{route('phone_models.index')}}"><button type="button" class="btn btn-primary m-t-15 waves-effect">
                                        << Back</button> </a> </div> <div class="col-lg-8 col-md-8 col-sm-10 col-xs-10">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')

@endpush

resources/views/admin/phone_models/edit.blade.php
@extends('layouts.dashboard.dash')
@section('title', $title)
@push('css')

@endpush
@section('content')

<style>
    .control-label:after {
        content: "*";
        color: red;
    }
</style>

<div class="container-fluid">
    <!-- Horizontal Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        {{ $title }}
                    </h2>
                </div>
                <div class="body">
                    <div class="col-lg-10 col-lg-offset-2 col-md-12">
                        <label for="required_field" class="control-label"></label><i> required field</i>
                    </div>
                    <form class="form-horizontal" action="{{ route('phone_models.update', $phone_models->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row{{ $errors->has('model_name') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
                                <label for="model_name" class="control-label">Model </label>
                            </div>
                            <div class="col-lg-6 col-md-8 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="model_name" id="model_name" class="form-control" value="{{ $phone_models->model_name }}" placeholder="ex-P30">
                                    </div>
                                </div>
                                @if ($errors->has('model_name'))
                                <span class="help-block">{{ $errors->first('model_name') }}</span>
                                @endif
                            </div>
                            <div class="col-lg-2"></div>
                        </div>
                        <div class="row{{ $errors->has('fs_mrp') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
                                <label for="fs_mrp" class="control-label">FS MRP&nbsp;<img src="{{ asset('assets/taka.png') }}" width="8" height="10"> </label>
                            </div>
                            <div class="col-lg-6 col-md-8 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="number" name="fs_mrp" id="fs_mrp" class="form-control" value="{{ $phone_models->mrp }}" placeholder="ex-15990">
                                    </div>
                                </div>
                                @if ($errors->has('fs_mrp'))
                                <span class="help-block">{{ $errors->first('fs_mrp') }}</span>
                                @endif
                            </div>
                            <div class="col-lg-2"></div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-5 form-control-label">
                                <label for="status">Status</label>
                            </div>
                            <div class="col-lg-6 col-md-8 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="">
                                        <select class="form-control selectpicker" name="status" id="status">
                                            <option value="1" {{$phone_models->status == 1 ? 'selected="selected"' : ''}}>Available</option>
                                            <option value="2" {{$phone_models->status == 2 ? 'selected="selected"' : ''}}>Disable</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2"></div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-4 col-md-4 col-sm-2 col-xs-2">
                                <a href="{{route('phone_models.index')}}"><button type="button" class="btn btn-primary m-t-15 waves-effect">
                                        << Back</button> </a> </div> <div class="col-lg-8 col-md-8 col-sm-10 col-xs-10">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')

@endpush

resources/views/admin/phone_models/list.blade.php
@extends('layouts.dashboard.dash')
@section('title', $title)
@push('css')

@endpush

@section('content')

<style>
    .fa.fa-bars {
        font-size: inherit !important;
    }

    .fa.fa-pencil-square-o {
        font-size: inherit !important;
    }

    .fa.fa-trash-o {
        font-size: inherit !important;
    }
</style>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                        <h2>
                            {{ $title }}
                        </h2>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                        <a href="{{route('phone_models.create')}}"><button type="button" class="btn bg-green waves-effect">Add
                                New</button></a>
                    </div>
                </div>
            </div>
            @if ($message = Session::get('msg'))
            <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {{ $message }}</em></div>
            @endif
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Model</th>
                                <th>FS MRP</th>
                                <th>Status</th>
                                <th>Added By</th>
                                <th>Date of creation</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Model</th>
                                <th>FS MRP</th>
                                <th>Status</th>
                                <th>Added By</th>
                                <th>Date of creation</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <?php $i = 1; ?>
                            @foreach ($models as $value)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $value->model_name }}</td>
                                <td><img src="{{ asset('assets/taka.png') }}" width="8" height="10">&nbsp;{{ $value->mrp }}</td>
                                @if($value->status == 1)
                                <td style="color: green;">Available</td>
                                @else
                                <td style="color: red;">Disable</td>
                                @endif
                                <td>{{ $value->name }}</td>
                                <td>{{ Carbon\Carbon::parse($value->created_at)->format('M d Y') }}</td>
                                <td>
                                    <form action="{{ route('phone_models.destroy',$value->id) }}" method="POST">

                                        <a class="btn btn-defauld" href="{{ route('phone_models.show', $value->id) }}"><i class="fa fa-bars" aria-hidden="true" title="view"></i></a>

                                        &nbsp;&nbsp; <a class="btn btn-primary" href="{{ route('phone_models.edit', $value->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true" title="edit"></i></a>

                                        @csrf
                                        @method('DELETE')

                                        &nbsp;&nbsp; <button class="btn btn-danger" type="submit" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o" aria-hidden="true" title="delete"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')

@endpush

resources/views/admin/phone_models/view.blade.php
@extends('layouts.dashboard.dash')
@section('title', $title)
@push('css')

@endpush
@section('content')
@foreach($phone_models as $value)
<div class="container-fluid">
    <!-- Horizontal Layout -->
    <div class="row clearfix">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
            <div class="card">
                <div class="header">
                    <h2>
                        {{ $title }}
                    </h2>
                </div>
                <div class="body">
                    <div class="row clearfix">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                            <strong>Model :</strong>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            {{$value->model_name}}
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                            <strong>FS MRP :</strong>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        <img src="{{ asset('assets/taka.png') }}" width="8" height="10">&nbsp;{{$value->mrp}}
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                            <strong>Status :</strong>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            @if($value->status == 1)
                            <p style="color: green;">Available</p>
                            @else
                            <p style="color: red;">Disable</p>
                            @endif
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                            <strong>Added By :</strong>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            {{$value->name}}
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                            <strong>Created At :</strong>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            {{ Carbon\Carbon::parse($value->created_at)->format('M d Y') }}
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                            <strong>Updated At :</strong>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            {{ Carbon\Carbon::parse($value->updated_at)->format('M d Y') }}
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 form-control-label">
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                            <a href="{{route('phone_models.index')}}"><button type="button" class="btn btn-primary m-t-15 waves-effect">
                                    << Back</button> </a> </div> </div> </div> </div> </div> </div> </div> @endforeach @endsection @push('js') @endpush