routes/web.php
<?php

use App\Http\Controllers\ReportController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

//Home page
Route::get('/', function () {
    return view('auth/login');
});

Route::get('/reset_password', 'PasswordResetController@index')->name('resetPassword');
Route::post('/reset_password', 'PasswordResetController@search_user')->name('getUser');
Route::post('/reset_password/confirmed', 'PasswordResetController@update')->name('password_reset');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('change_password', 'PasswordChangeController');
});


Route::group(['middleware' => 'auth', 'middleware' => ['role:supadmin|salescenter|servicepoint']], function () {
    Route::post('/chk_disclaimer', 'HomeController@disclaimer')->name('chk_disclaimer');
    Route::resource('sales', 'SaleController');
    Route::post('/get_fscode', 'SaleController@get_fs')->name('get_fscode');
    Route::post('/get_service_type_price_range', 'SaleController@get_service_type_price_range')->name('get_service_type_price_range');
    Route::post('/sales_report', 'SaleController@date_wise_sales_report')->name('sales_report');
    Route::post('/get_mrp', 'SaleController@get_mrp')->name('get_mrp');
    Route::post('/get_imei_info', 'SaleController@get_info_by_imei')->name('get_imei_info');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|servicepoint|callcenter']], function () {
    Route::post('/chk_service_disclaimer', 'ServicePointController@disclaimer_service')->name('chk_service_disclaimer');
    Route::resource('servicepoint', 'ServicePointController');
    Route::post('servicepoint', 'ServicePointController@search')->name('search');
    Route::post('servicepoint/search_by_phone_number', 'ServicePointController@search_by_phone_number')->name('search_by_phone');
    Route::post('servicepoint/search_by_serviceType', 'ServicePointController@search_by_serviceType')->name('search_by_service_type');
    Route::post('servicepoint/record_history', 'ServicePointController@store')->name('record_history');
    Route::post('servicepoint/delivery', 'ServicePointController@handset_delivery')->name('delivery');
    Route::post('servicepoint/notification', 'ServicePointController@send_early_notification')->name('notification');
    Route::post('servicepoint/verify', 'ServicePointController@verify')->name('verify_otp');
    Route::post('servicepoint/displayImage', 'ServicePointController@display_sales_image')->name('displayImage');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin']], function () {
    Route::get('/store_wise', 'ReportController@store_wise')->name('store');
    Route::post('/store_wise', 'ReportController@store_wise_report')->name('store_wise_report');
    Route::get('/date_wise', 'ReportController@date_wise')->name('date');
    Route::post('/date_wise', 'ReportController@date_wise_report_search')->name('date_wise_reaport');
    Route::get('/imei_wise', 'ReportController@imei_wise')->name('imei');
    Route::post('/imei_wise', 'ReportController@imei_wise_report')->name('imei_wise_report');
    Route::get('/head_office', 'ReportController@head_office')->name('head');
    Route::post('/showImage', 'ReportController@display_image')->name('show_image');
    Route::post('/deleteSale/{fscode}', 'ReportController@delete_sale')->name('delete_sale');
});


Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin']], function () {
    Route::resource('users', 'UsersController');
    Route::resource('permission', 'PermissionController');
    Route::resource('roles', 'RolesController');
    Route::resource('outlet', 'OutletController');
    Route::resource('import', 'ImportExportController');
    Route::delete('import', 'ImportExportController@destroy_all')->name('delete_all');
    Route::resource('txtimport', 'TxtFileImportController');
    Route::delete('txtimport', 'TxtFileImportController@destroy_all')->name('txt_delete_all');
    Route::resource('download', 'FileDownloadController');
    Route::resource('imeichange', 'ImeiChangeController');
    Route::post('/imeichange', 'ImeiChangeController@get_details_by_imei')->name('imeidetail');
    Route::get('/extractfile', 'FileExtractionController@index')->name('file_extraction');
    Route::post('/extractfile', 'FileExtractionController@fileExtraction')->name('file_extraction');
    Route::resource('tiers', 'TierController');
    Route::resource('phone_models', 'PhoneModelController');
    Route::resource('import_imei', 'ImeiController');
    Route::get('/download_sample_imei', 'FileDownloadController@imei_sample')->name('download_sample_imei');
    Route::get('/download_sample_bulk_user_creation', 'FileDownloadController@bulk_user_creation_sample')->name('download_sample_bulk_user_creation');
    Route::get('/bulk_user_creation', 'UsersController@get_bulk_user_creation_view')->name('create_bulk_user');
    Route::post('/bulk_user_creation', 'UsersController@bulk_user_creation')->name('bulk_user');
    Route::resource('bongoTvCodes', 'BongoTvCodeController');
    Route::delete('bongoTvCodes', 'BongoTvCodeController@destroy_unusedCodes')->name('delete_unused_codes');
    Route::get('/download_sample_bongoTvCodes', 'FileDownloadController@bongoTvCodesSample')->name('download_sample_bongoTvCodes');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|insurance|admin']], function () {
    Route::get('/ins_sales_report', 'ReportController@insurance_sales')->name('ins_sales');
    Route::post('/ins_sales_report', 'ReportController@insurance_sales_report')->name('insurance_sales_report');
    Route::post('/insImageDisplay', 'ReportController@display_image')->name('ins_display_image');
    Route::get('/ins_service_report', 'ReportController@insurance_service')->name('ins_service');
    Route::post('/ins_service_report', 'ReportController@insurance_service_report')->name('insurance_service_report');
    Route::post('/insServiceImageDisplay', 'ReportController@ins_display_image')->name('ins_display_service_image');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin|insurance']], function () {
    Route::get('/date_wise_claim_search', 'ReportController@get_date_wise_claim_report')->name('date_wise_claim_search');
    Route::post('/date_wise_claim_search', 'ReportController@date_wise_claim_report_search')->name('date_wise_claim_report');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth', 'middleware' => ['role:supadmin|admin|insurance|servicepoint|callcenter']], function () {
    Route::get('/date_wise_claim_search', 'ReportController@get_date_wise_claim_report')->name('date_wise_claim_search');
    Route::post('/date_wise_claim_search', 'ReportController@date_wise_claim_report_search')->name('date_wise_claim_report');
    Route::post('/insServiceImageDisplay', 'ReportController@ins_display_image')->name('ins_display_service_image');
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:supadmin|salescenter|callcenter|servicepoint']], function () {
    Route::post('/verify_sales', 'SaleController@verifyOtp')->name('otpVerify');
    Route::post('/resend_otp', 'SaleController@resendOtp')->name('resend_otp');
    Route::post('/submit_without_otp', 'SaleController@submitWithoutOtp')->name('submit_without_otp');
    Route::post('/verify_sale/{id}', 'SaleController@saleVerification')->name('sale_verification');
    Route::resource('sales', 'SaleController');
    Route::post('/sales_report', 'SaleController@date_wise_sales_report')->name('sales_report');
});

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Database\Eloquent\ModelNotFoundException as ModelNotFoundException;

use App\Http\Controllers\Controller;
use App\Outlet;
use Illuminate\Http\Request;
use App\User;
use App\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = DB::table('users')
            ->select('users.*', 'outlets.store_name', 'roles.display_name')
            ->join('role_user', 'role_user.user_id', '=', 'users.id')
            ->join('roles', 'roles.id', '=', 'role_user.role_id')
            ->leftjoin('outlets', 'outlets.id', '=', 'users.store_id')
            ->get();

        $params = [
            'title' => 'Users List',
            'users' => $users,
        ];

        return view('admin.users.users_list')->with($params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        $stores = Outlet::all();

        $params = [
            'title' => 'Create User',
            'roles' => $roles,
            'stores' => $stores,
        ];

        return view('admin.users.users_create')->with($params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'username' => 'required|string|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
            'store_id' => 'required',
            'role_id' => 'required',
        ]);

        $user = User::create([
            'name' => $request->input('name'),
            'username' => $request->input('username'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'store_id' => $request->input('store_id'),
        ]);

        $role = Role::find($request->input('role_id'));

        $user->attachRole($role);

        return redirect()->route('users.index')->with('msg', "The user $user->name has successfully been created.");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $users = DB::table('users')
                ->select('users.*', 'outlets.store_name', 'roles.display_name')
                ->join('role_user', 'role_user.user_id', '=', 'users.id')
                ->join('roles', 'roles.id', '=', 'role_user.role_id')
                ->leftjoin('outlets', 'outlets.id', '=', 'users.store_id')
                ->where('users.id', '=', $id)
                ->get();

            $params = [
                'title' => 'Confirm Delete Record',
                'users' => $users,
            ];

            return view('admin.users.users_view')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $users = DB::table('users')
                ->select('users.*', 'outlets.store_name', 'roles.display_name', 'roles.id as role_id')
                ->join('role_user', 'role_user.user_id', '=', 'users.id')
                ->join('roles', 'roles.id', '=', 'role_user.role_id')
                ->leftjoin('outlets', 'outlets.id', '=', 'users.store_id')
                ->where('users.id', '=', $id)
                ->get();

            $roles = Role::all();
            $stores = Outlet::all();
            // $roles = Role::with('permissions')->get();
            // $permissions = Permission::all();

            $params = [
                'title' => 'Edit User',
                'users' => $users,
                'roles' => $roles,
                'stores' => $stores,
            ];

            return view('admin.users.users_edit')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $user = User::findOrFail($id);

            $this->validate($request, [
                'name' => 'required|string|max:255',
                'username' => 'required|string|max:255|',
                'store_id' => 'required',
                'role_id' => 'required',
            ]);

            $user->name = $request->input('name');
            $user->username = $request->input('username');
            $user->email = $request->input('email');
            $user->store_id = $request->input('store_id');

            $user->save();

            // Update role of the user
            $roles = $user->roles;

            foreach ($roles as $key => $value) {
                $user->detachRole($value);
            }

            $role = Role::find($request->input('role_id'));

            $user->attachRole($role);

            // Update permission of the user
            //$permission = Permission::find($request->input('permission_id'));
            //$user->attachPermission($permission);

            return redirect()->route('users.index')->with('msg', "The user $user->name has successfully been updated.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $user = User::findOrFail($id);

            // Detach from Role
            $roles = $user->roles;

            foreach ($roles as $key => $value) {
                $user->detachRole($value);
            }

            $user->delete();
            // if($user->store_id != null){
            //     Outlet::where('id', '=', $user->store_id)->delete();
            // }

            return redirect()->route('users.index')->with('msg', "The user $user->name has successfully been deleted.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    public function get_bulk_user_creation_view()
    {
        $params = [
            'title' => 'Create Bulk User'
        ];

        return view('admin.users.bulk_user_creation')->with($params);
    }

    public function bulk_user_creation(Request $request)
    {

        $this->validate($request, [
            'upload_user' => 'required|mimes:txt'
        ]);

        $file = fopen($_FILES['upload_user']['tmp_name'], 'r');
        while (!feof($file)) {
            $content = trim(fgets($file));
            $carray = explode('|', $content);
            // echo '<pre>'; print_r($carray);die;
            if (count($carray) > 7) {
                return back()->with('msg', 'File not formated properly. Please download the sample file');
            } else {
                list($store_name, $user_id, $password, $store_address, $contact_number, $area, $role) = $carray;

                //auto generated store code
                $last_code = DB::table('outlets')->latest('store_code')->first();
                if (!empty($last_code)) {
                    $new_store_code =  str_pad((int) $last_code->store_code + 1, 4, 0, STR_PAD_LEFT);
                } else {
                    $new_store_code = '0001';
                }

                $store = Outlet::updateOrCreate([
                    'store_name' => $store_name
                ], [
                    'store_code' => $new_store_code,
                    'address' => $store_address,
                    'district' => $area,
                    'contact_details' => $contact_number
                ]);

                // generate random 8 char password from below chars
                // $random = str_shuffle('abcdefghjklmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ234567890!$%^&!$%^&');
                // $password = substr($random, 0, 8);

                $user = User::updateOrCreate([
                    'username' => $user_id
                ], [
                    'name' => $store_name,
                    'password' => Hash::make($password),
                    'store_id' => $store->id
                ]);

                $find_role = Role::find($role);

                $user->attachRole($find_role);
            }
        }
        return back()->with('msg', 'Data imported successfully.');
    }
}

resources/views/admin/users/users_create.blade.php
@extends('layouts.dashboard.dash')
@section('title','User Create')
@push('css')

@endpush

@section('content')

<style>
    .control-label:after {
        content: "*";
        color: red;
    }

    .btn-group.bootstrap-select .dropdown-menu.open {
        overflow: unset !important;
    }
</style>

<div class="container-fluid">
    <!-- Horizontal Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        {{ $title }}
                    </h2>
                </div>
                <div class="body">
                    <label for="required_field" class="control-label"></label><i> required field</i>
                    <form class="form-horizontal" action="{{ route('users.store') }}" method="POST">
                        @csrf
                        <div class="row{{ $errors->has('name') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="name" class="control-label">Name </label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="name" id="name" value="{{ Request::old('name') ?: '' }}" class="form-control" placeholder="Enter role name">
                                    </div>
                                </div>
                                @if ($errors->has('name'))
                                <span class="help-block">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row{{ $errors->has('username') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="username" class="control-label">Username </label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="username" id="username" value="{{ Request::old('username') ?: '' }}" class="form-control" placeholder="Enter username">
                                    </div>
                                </div>
                                @if ($errors->has('username'))
                                <span class="help-block">{{ $errors->first('username') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="email">E-mail</label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="email" name="email" id="email" value="{{ Request::old('email') ?: '' }}" class="form-control" placeholder="Enter E-mail">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row{{ $errors->has('password') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="password" class="control-label">Password </label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="password" name="password" id="password" class="form-control" value="{{ Request::old('password') ?: '' }}" placeholder="Enter password" autocomplete="new-password">
                                    </div>
                                </div>
                                @if ($errors->has('password'))
                                <span class="help-block">{{ $errors->first('password') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="confirm_password" class="control-label">Confirm Password </label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="password" name="password_confirmation" id="password-confirm" class="form-control" placeholder="Re-enter password" autocomplete="new-password">
                                    </div>
                                </div>
                                @if ($errors->has('confirm_password'))
                                <span class="help-block">{{ $errors->first('confirm_password') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="row{{ $errors->has('store_id') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="store_id" class="control-label">Store </label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="demo-checkbox">
                                        <select class="form-control selectpicker" data-live-search="true" id="store_id" name="store_id">
                                            <option value="">Select One</option>
                                            @if(count($stores))
                                            @foreach($stores as $store)
                                            <option value="{{$store->id}}" @if (old('store_id')=="$store->id" ) {{ 'selected' }} @endif>{{$store->store_name}}</option>
                                            @endforeach
                                            @endif
                                        </select>
                                        @if ($errors->has('store_id'))
                                        <span class="help-block">{{ $errors->first('store_id') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row{{ $errors->has('role_id') ? ' has-error' : '' }} clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label for="role_id" class="control-label">Role </label>
                            </div>
                            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="demo-checkbox">
                                        <select class="form-control" id="role_id" name="role_id">
                                            <option value="">Select One</option>
                                            @if(count($roles))
                                            @foreach($roles as $row)
                                            <option value="{{$row->id}}" @if (old('role_id')=="$row->id" ) {{ 'selected' }} @endif>{{$row->display_name}}</option>
                                            @endforeach
                                            @endif
                                        </select>
                                        @if ($errors->has('role_id'))
                                        <span class="help-block">{{ $errors->first('role_id') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                <a href="{{route('users.index')}}"><button type="button" class="btn btn-primary m-t-15 waves-effect">
                                        << Back</button> </a> </div> <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')

@endpush

resources/views/admin/users/users_list.blade.php
@extends('layouts.dashboard.dash')
@section('title','User List')
@push('css')

@endpush

@section('content')

<style>
  .fa.fa-bars {
    font-size: inherit !important;
  }

  .fa.fa-pencil-square-o {
    font-size: inherit !important;
  }

  .fa.fa-trash-o {
    font-size: inherit !important;
  }
</style>

<!-- Exportable Table -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <div class="row">
          <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
            <h2>
              {{ $title }}
            </h2>
          </div>
          {{-- @role('basic_user') --}}
          <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
            <a href="{{route('users.create')}}"><button type="button" class="btn bg-green waves-effect">Add
                New</button></a>
          </div>
          {{-- @endrole --}}
        </div>
      </div>
      @if ($message = Session::get('msg'))
      <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {{ $message }}</em></div>
      @endif
      <div class="body">
        <div class="table-responsive">
          <table class="table table-bordered table-striped table-hover dataTable js-exportable">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Username</th>
                <th>E-mail</th>
                <th>Assigned Store</th>
                <th>Assigned Role</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Username</th>
                <th>E-mail</th>
                <th>Assigned Store</th>
                <th>Assigned Role</th>
                <th>Actions</th>
              </tr>
            </tfoot>
            <tbody>
              <?php $i = 1; ?>
              @foreach ($users as $user)

              <tr>
                <td>{{ $i++ }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->username }}</td>
                <td>{{ $user->email }}</td>
                @if($user->store_name == null)
                <td>Not a store user</td>
                @else
                <td>{{ $user->store_name }}</td>
                @endif
                <td>{{ $user->display_name }}</td>
                <td>
                  <form action="{{ route('users.destroy',$user->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="row">
                      <div class="col-sm-4">
                        <a class="btn btn-defauld" href="{{ route('users.show', $user->id) }}"><i class="fa fa-bars" aria-hidden="true" title="view"></i></a>
                      </div>
                      <div class="col-sm-4">
                        <a class="btn btn-primary" href="{{ route('users.edit', $user->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true" title="edit"></i></a>
                      </div>
                      <div class="col-sm-4">
                        <button class="btn btn-danger" type="submit" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o" aria-hidden="true" title="delete"></i></button>
                      </div>
                    </div>
                  </form>
                </td>
              </tr>

              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- #END# Exportable Table -->
@endsection

@push('js')

@endpush